// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkujwqwlxgecbshgkwlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrdWp3cXdseGdlY2JzaGdrd2xyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2Nzk5MzYsImV4cCI6MjA1ODI1NTkzNn0.7ShoKGmG_33uZUfPyLQUlI37usYJ2QboYEQVLz-d6Gg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);